### ISSUE TITLE
Database connectivity/abstraction

### ISSUE THREAD

**Issue by verdog** [ccowmu/ccawmunity#14]
I'd like there to be an ability to connect to a database to enable some long-term storage capability. 

I'd like to make it as abstract and easy to use as possible. I think anyone using a database would only be interested in storing/retrieving values. So the capability would be limited to something like `store(variable, place)` and `retrieve(variable, from_here)`

Under the hood, I think the database should be specified upon startup. This way, people can use their own databases if they want to. I'm envisioning one "master" database that anyone can use, with the option of pointing it to your own database.

I think mysql is a perfectly fine choice for a database.

**Comment by kokorohakai** [comment]
I think it might even be better to setup tables for the command in specific. Would it be possible to auto get the table(s) for  command as they are used? Although are you sure it's always 1:1? Don't forget a command such as the .quote command in my version of the bot requires user and quote to be stored in the same row. so it's a 1 to many relation.

I've written an abstracted data model in php before, and it can get  little hairy. it's going to need a little more than simple store and retrieve methods. But it's not to say it can't be done.

**Comment by verdog** [comment]
it works!
