### ISSUE TITLE
External listening capability

### ISSUE THREAD

**Issue by verdog** [ccowmu/ccawmunity#31]
It's becoming apparent that giving the bot some ability to "listen" to for external signals would be very handy.

I'm not sure how exactly this works, but I'd imagine that it goes something like this:

A new kind of class is created for the bot. Instead of only commands, we have commands and "listeners" (working title). Listeners listen on a dedicated port for incoming POST (and other?) requests. 

Each incoming request might have to have a dedicated way to specify which function it is intended for. For example, should an incoming request about a new CTF be sent to the portion of the code that posts a message when a new PR is submitted?

This might be difficult, especially if we were to set up a webhook from an external service to point to the bot. We have no control of what the external service sends the bot, so how do we direct it to the right function?

---

So my idea is: *an external source* sends the bot a request, and the bot knows how to respond (by posting something in a certain channel). 

This issue was created with an intention of discussion, so feel free to post thoughts.

**Comment by Xwaffle1** [comment]
It should be relatively easy, basically on a PHP script we can listen for specific POST requests and pass onto the bot information.
